let arr1 = [1, 2, 3, 4, 5]
let arr2 = ["a", "b", "c"]
let arr3 = [true, false, 1, 2.5, "str"]
let arr4 = [ [1,2], [3,4,5], ["x","y"] ]
let arr5 = [1, 2, 3]       # trailing comma
let arr6 = [ 1 , 2 , 3 ]    # whitespace everywhere

fn add(a, b) { 
    
    return a + b }
let result = add(3, add(4, 5))
let nestedArr = [ add(1,2), add(3,4), [ add(5,6), 7 ] ]

let complex = (3 + 4 * 2) / (1 - 5) || true && false
let mix = 3 + 4 * (2 - 1) / 5 == 7 && (true || false)

let name = "Julianne"
let greeting = f"Hello, {name}!"
let nestedStr = f"Sum: { add(1,2) } and array: {[1,2,3]}"

fn crazy(a, b) {
    let arr = [ a, b, add(a,b), [1,2,3], f"{a}-{b}" ]
    return arr[2] * add(arr[0], arr[1])
}

let result = crazy(3, add(2, 1)) || false